#### general settings
name: Net_2input_1fps_training_l1_lr3e-4_2
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: test_train
    mode: LQGT
    dataroot_GT: /home/rchenbe/rchenbe/BasicSR-netD12-gray_dual_input/data_samples/1fps/train/HR
    dataroot_LQ: /home/rchenbe/rchenbe/BasicSR-netD12-gray_dual_input/data_samples/1fps/train/SRRF
    dataroot_WF: /home/rchenbe/rchenbe/BasicSR-netD12-gray_dual_input/data_samples/1fps/train/WF

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 8
    GT_size: 256
    use_flip: true
    use_rot: true
#    color: RGB -> grey img input
  val:
    name: test_vali
    mode: LQGT
    dataroot_GT: /home/rchenbe/rchenbe/BasicSR-netD12-gray_dual_input/data_samples/1fps/validate/HR
    dataroot_LQ: /home/rchenbe/rchenbe/BasicSR-netD12-gray_dual_input/data_samples/1fps/validate/SRRF
    dataroot_WF: /home/rchenbe/rchenbe/BasicSR-netD12-gray_dual_input/data_samples/1fps/validate/WF
    
#### network structures
network_G:
  which_model_G: RRDBNet
  # in_nc for netG: LR+WF
  in_nc: 2
  out_nc: 1
  nf: 64
  nb: 23

network_D:
  which_model_D: discriminator_vgg_256 
  in_nc: 1
  nf: 64

network_D2:
  which_model_D2: patch_GAN
  # in_nc for netD2: LR+WF+HR
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ~
  #pretrain_model_G: ~
  strict_load: true
  resume_state: ~
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 3e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 3e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  #lr_steps: [150000, 200000,250000,300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 1 # 0.01
  fft_criterion: l1
  fft_weight: 0 #0
  feature_criterion: l1
  feature_weight: 0 #
  gan_type: ragan  # gan | ragan
  gan_weight: 0 #!!float 2.5e-4

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 100

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 100
